// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"time"
)

type Role struct {
	ID   int64
	Name string
}

type User struct {
	ID        int64
	Username  string
	Firstname *string
	Activated bool
	CreatedAt time.Time
}

type UserRole struct {
	UserID int64
	RoleID int64
}
