// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"context"
)

type Querier interface {
	AssignUserRole(ctx context.Context, arg AssignUserRoleParams) error
	GetAllUser(ctx context.Context) ([]User, error)
	GetRole(ctx context.Context, name string) (Role, error)
	GetUser(ctx context.Context, id int64) (GetUserRow, error)
	InsertUser(ctx context.Context, arg InsertUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
